<?php
/**
 * Product catalogue — single source of truth for shop cards.
 * Sizes: S (13"), M (15"), L (20") with per-size pricing.
 */

return [
    [
        'id' => 'morning-light',
        'title' => 'Morning Light',
        'description' => 'Soft colour studies from quiet mornings in the studio, layered until the light felt true.',
        'image' => 'images/artwork/image-1.jpeg',
        'image_alt' => 'Morning Light — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'harbour-memory',
        'title' => 'Harbour Memory',
        'description' => 'Drawn from walks along the Irish coast — salt air, shifting greys, and the warmth of colour that remains when the weather clears.',
        'image' => 'images/artwork/image-2.jpeg',
        'image_alt' => 'Harbour Memory — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'marigold-garden',
        'title' => 'Marigold Garden',
        'description' => 'Inspired by gardens of memory — marigold golds, deep greens, and the quiet joy of watching colour bloom.',
        'image' => 'images/artwork/image-3.jpeg',
        'image_alt' => 'Marigold Garden — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 95, 'compare_at' => 135],
            'M' => ['label' => '15"', 'price' => 125, 'compare_at' => 165],
            'L' => ['label' => '20"', 'price' => 155, 'compare_at' => 205],
        ],
    ],
    [
        'id' => 'quiet-room',
        'title' => 'Quiet Room',
        'description' => 'An interior study of soft shadows and warm neutrals — the kind of light that settles into a room in late afternoon.',
        'image' => 'images/artwork/image-4.jpeg',
        'image_alt' => 'Quiet Room — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'river-stones',
        'title' => 'River Stones',
        'description' => 'Smooth forms and muted earth tones — pebbles, water, and the patience of looking closely.',
        'image' => 'images/artwork/image-5.jpeg',
        'image_alt' => 'River Stones — artwork by Lakshmi Sridhar',
        'tags' => ['print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 79, 'compare_at' => 119],
            'M' => ['label' => '15"', 'price' => 109, 'compare_at' => 149],
            'L' => ['label' => '20"', 'price' => 139, 'compare_at' => 189],
        ],
    ],
    [
        'id' => 'ember-dusk',
        'title' => 'Ember Dusk',
        'description' => 'Warm peanut and slate tones at the edge of evening — a sky that holds onto colour just a little longer.',
        'image' => 'images/artwork/image-6.jpeg',
        'image_alt' => 'Ember Dusk — artwork by Lakshmi Sridhar',
        'tags' => ['original'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 99, 'compare_at' => 139],
            'M' => ['label' => '15"', 'price' => 129, 'compare_at' => 169],
            'L' => ['label' => '20"', 'price' => 159, 'compare_at' => 209],
        ],
    ],
    [
        'id' => 'studio-piece-07',
        'title' => 'Studio Piece 07',
        'description' => 'A recent studio piece — layered slowly, colour by colour.',
        'image' => 'images/artwork/image-17.jpeg',
        'image_alt' => 'Studio Piece 07 — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'studio-piece-08',
        'title' => 'Studio Piece 08',
        'description' => 'A recent studio piece — layered slowly, colour by colour.',
        'image' => 'images/artwork/image-18.jpeg',
        'image_alt' => 'Studio Piece 08 — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'studio-piece-09',
        'title' => 'Studio Piece 09',
        'description' => 'A recent studio piece — layered slowly, colour by colour.',
        'image' => 'images/artwork/image-19.jpeg',
        'image_alt' => 'Studio Piece 09 — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'studio-piece-10',
        'title' => 'Studio Piece 10',
        'description' => 'A recent studio piece — layered slowly, colour by colour.',
        'image' => 'images/artwork/image-20.jpeg',
        'image_alt' => 'Studio Piece 10 — artwork by Lakshmi Sridhar',
        'tags' => ['original'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 99, 'compare_at' => 139],
            'M' => ['label' => '15"', 'price' => 129, 'compare_at' => 169],
            'L' => ['label' => '20"', 'price' => 159, 'compare_at' => 209],
        ],
    ],
    [
        'id' => 'studio-piece-11',
        'title' => 'Studio Piece 11',
        'description' => 'A recent studio piece — layered slowly, colour by colour.',
        'image' => 'images/artwork/image-21.jpeg',
        'image_alt' => 'Studio Piece 11 — artwork by Lakshmi Sridhar',
        'tags' => ['print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 79, 'compare_at' => 119],
            'M' => ['label' => '15"', 'price' => 109, 'compare_at' => 149],
            'L' => ['label' => '20"', 'price' => 139, 'compare_at' => 189],
        ],
    ],
];
