<?php
/**
 * Product catalogue — single source of truth for shop cards.
 * Sizes: A1, A2, A3. Stored original prices; prints are 50% on the site.
 */

return [
    [
        'id' => 'morning-light',
        'title' => 'The Reader',
        'description' => 'A white figure seated with an open book, chin resting in the hand — a quiet study of thought.',
        'image' => 'images/artwork/thinker-reading.jpeg',
        'image_alt' => 'The Reader — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'harbour-memory',
        'title' => 'Krishna',
        'description' => 'Lord Krishna with flute, jasmine, and falling red petals, drawn in colour on a field of gold.',
        'image' => 'images/artwork/krishna-petals.jpeg',
        'image_alt' => 'Krishna — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'marigold-garden',
        'title' => 'Crown of Thorns',
        'description' => 'A graphite study of Christ, eyes closed, wearing the crown of thorns.',
        'image' => 'images/artwork/crown-of-thorns.jpeg',
        'image_alt' => 'Crown of Thorns — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 95, 'compare_at' => 135],
            'M' => ['label' => '15"', 'price' => 125, 'compare_at' => 165],
            'L' => ['label' => '20"', 'price' => 155, 'compare_at' => 205],
        ],
    ],
    [
        'id' => 'quiet-room',
        'title' => 'Two Women',
        'description' => 'Two women in traditional jewellery and jasmine — one in profile, one seen from behind.',
        'image' => 'images/artwork/two-women.jpeg',
        'image_alt' => 'Two Women — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'river-stones',
        'title' => 'The Pug',
        'description' => 'A colour-pencil portrait of a pug, tongue out, drawn with the softness of fur and the shine of a wet nose.',
        'image' => 'images/artwork/the-pug.jpeg',
        'image_alt' => 'The Pug — artwork by Lakshmi Sridhar',
        'tags' => ['print'],
        'status' => 'available',
        'featured' => true,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 79, 'compare_at' => 119],
            'M' => ['label' => '15"', 'price' => 109, 'compare_at' => 149],
            'L' => ['label' => '20"', 'price' => 139, 'compare_at' => 189],
        ],
    ],
    [
        'id' => 'ember-dusk',
        'title' => 'Krishna with Flute',
        'description' => 'A graphite study of Krishna, flute in hand, crown and birds drawn in careful light.',
        'image' => 'images/artwork/krishna-flute.jpeg',
        'image_alt' => 'Krishna with Flute — artwork by Lakshmi Sridhar',
        'tags' => ['original'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 99, 'compare_at' => 139],
            'M' => ['label' => '15"', 'price' => 129, 'compare_at' => 169],
            'L' => ['label' => '20"', 'price' => 159, 'compare_at' => 209],
        ],
    ],
    [
        'id' => 'studio-piece-07',
        'title' => 'Two Women',
        'description' => 'Two women in traditional jewellery and jasmine — one in profile, one seen from behind.',
        'image' => 'images/artwork/two-women-study.jpeg',
        'image_alt' => 'Two Women — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'studio-piece-08',
        'title' => 'The Warrior',
        'description' => 'A colour-pencil portrait of a man in red face paint and a single braid.',
        'image' => 'images/artwork/the-warrior.jpeg',
        'image_alt' => 'The Warrior — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'studio-piece-09',
        'title' => 'Red Apples',
        'description' => 'A close still life of red apples — water on the skin, leaves still attached.',
        'image' => 'images/artwork/red-apples.jpeg',
        'image_alt' => 'Red Apples — artwork by Lakshmi Sridhar',
        'tags' => ['original', 'print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 89, 'compare_at' => 129],
            'M' => ['label' => '15"', 'price' => 119, 'compare_at' => 159],
            'L' => ['label' => '20"', 'price' => 149, 'compare_at' => 199],
        ],
    ],
    [
        'id' => 'studio-piece-10',
        'title' => 'The Leopard',
        'description' => 'A leopard in profile, spots and whiskers drawn in graphite on a warm ground.',
        'image' => 'images/artwork/the-leopard.jpeg',
        'image_alt' => 'The Leopard — artwork by Lakshmi Sridhar',
        'tags' => ['original'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 99, 'compare_at' => 139],
            'M' => ['label' => '15"', 'price' => 129, 'compare_at' => 169],
            'L' => ['label' => '20"', 'price' => 159, 'compare_at' => 209],
        ],
    ],
    [
        'id' => 'studio-piece-11',
        'title' => 'Drawing Kolam',
        'description' => 'A woman in a yellow sari drawing a kolam, seen from above — white lines finding their pattern.',
        'image' => 'images/artwork/drawing-kolam.jpeg',
        'image_alt' => 'Drawing Kolam — artwork by Lakshmi Sridhar',
        'tags' => ['print'],
        'status' => 'available',
        'featured' => false,
        'default_size' => 'S',
        'sizes' => [
            'S' => ['label' => '13"', 'price' => 79, 'compare_at' => 119],
            'M' => ['label' => '15"', 'price' => 109, 'compare_at' => 149],
            'L' => ['label' => '20"', 'price' => 139, 'compare_at' => 189],
        ],
    ],
];
